### ISSUE TITLE
Compile Errors

### ISSUE THREAD

**Issue by dedimark** [Teamkiller324/SwapTeam-Manager#2]
Sourcemod - 1.11-build-6911

Tklib from - https://github.com/Teamkiller324/Tklib/tree/main/Main/scripting/include

//// swapteam_manager.sp
//
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\tf2.inc(1958) : warning 217: inconsistent indentation (did you mix tabs and spaces?)
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\tf2.inc(2116) : warning 217: inconsistent indentation (did you mix tabs and spaces?)
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\tf2.inc(2722) : warning 217: inconsistent indentation (did you mix tabs and spaces?)
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\tf2.inc(2729) : warning 217: inconsistent indentation (did you mix tabs and spaces?)
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\tf2.inc(2736) : warning 217: inconsistent indentation (did you mix tabs and spaces?)
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\tf2.inc(2743) : warning 217: inconsistent indentation (did you mix tabs and spaces?)
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\entities.inc(329) : error 017: undefined symbol "clsname"
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\cstrike.inc(684) : error 017: undefined symbol "CSS_Item_DefuserKit"
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\cstrike.inc(697) : error 017: undefined symbol "CSGO_Knife"
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\csgo.inc(693) : error 017: undefined symbol "CSGO_GetClassnameDefindex"
// G:\N\PLUGINS\Sourcemod 2023\compile\1.11 - build 6911 - Compiler\include\tklib\clients.inc(1037) : error 017: undefined symbol "clients"
// swapteam_manager.sp(107) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(113) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(123) : error 017: undefined symbol "GetClientOfPlayername"
// swapteam_manager.sp(125) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(274) : error 017: undefined symbol "CPrintToChatAll"
// swapteam_manager.sp(275) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(283) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(290) : error 017: undefined symbol "GetClientOfPlayername"
// swapteam_manager.sp(292) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(301) : error 017: undefined symbol "CPrintToChatAll"
// swapteam_manager.sp(302) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(310) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(318) : error 017: undefined symbol "GetClientOfPlayername"
// swapteam_manager.sp(318) : error 017: undefined symbol "GetClientOfPlayername"
// swapteam_manager.sp(320) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(324) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(332) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(379) : error 017: undefined symbol "CPrintToChatAll"
// swapteam_manager.sp(380) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(392) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(400) : error 017: undefined symbol "GetClientOfPlayername"
// swapteam_manager.sp(402) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(412) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(416) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(423) : error 017: undefined symbol "CPrintToChatAll"
// swapteam_manager.sp(424) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(432) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(439) : error 017: undefined symbol "GetClientOfPlayername"
// swapteam_manager.sp(441) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(457) : error 017: undefined symbol "CPrintToChatAll"
// swapteam_manager.sp(458) : error 017: undefined symbol "CPrintToChat"
// swapteam_manager.sp(478) : error 017: undefined symbol "CPrintToChatAll"
// swapteam_manager.sp(479) : error 017: undefined symbol "CPrintToChat"
//
// 38 Errors.
//
// Compilation Time: 1.3 sec

Thank you @Teamkiller324

**Comment by nukkonyan** [comment]
You need multicolors include for coloured chat printing.
I will update the plugin to reflect latest tklib changes.
Atm the plugin contains ancient code.
